### ISSUE TITLE
Convert to dlsym instead of using headers

### ISSUE THREAD

**Issue by sliceofcode** [sliceofcode/CheeseLauncher-Legacy#6]
- Remove @KsyMC's headers.
- Use `dlsym` instead of headers.

**Comment by InusualZ** [comment]
I really doesn't approve that. Even zhuowei use Minecraft structs in his code. With the header you don't have to simulate the c++ class thingy.

**Comment by sliceofcode** [comment]
It does make things better to read. @jose-vm, any thoughts on this?

**Comment by jose-vm** [comment]
I know, but imagine updating headers each update arrives?
Imo, since MCPE updates are every 2 months now, I would prefer dlsym.
Lets vote. I vote dlsym.

**Comment by InusualZ** [comment]
Well, I vote for headers.

You only have to get the full class once... Because basically in every update they just add new field or something. They don't modify the hole class

**Comment by sliceofcode** [comment]
@InusualZ Are the changes easy to find? I certainly cannot reconstruct headers.

**Comment by InusualZ** [comment]
Well, that's the only downside (You have to know ARM Assembly) that I can think

**Comment by jose-vm** [comment]
In case we need structs, we could typedef structs in case we use dlsym

**Comment by jose-vm** [comment]
We should have a repo full of MCPE dumps so we could dif them and see the changes the constructors were made, so we don't have to make structs over and over from zero.
